In [1]:
from seqlearn.hmm import MultinomialHMM
from seqlearn.perceptron import StructuredPerceptron
import numpy as np
from numpy.testing import assert_array_almost_equal,assert_array_equal
import os
from sklearn.externals import joblib
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import mean_squared_error, accuracy_score

In [2]:
def read_pkls():
	data = []
	labels = []
	files = os.listdir(os.path.join(os.getcwd(),'data'))
	files = sorted(files)
	print(files)
	for file in files:
		X = joblib.load(os.path.join(os.getcwd(),'data',file))
		data.append(X)
	files = os.listdir(os.path.join(os.getcwd(),'labels'))
	files = sorted(files)
	print(files)
	for file in files:
		Y = joblib.load(os.path.join(os.getcwd(),'labels',file))
		labels.append(Y)
	return data, labels

In [3]:
def evaluate_classifier(X,Y,clf):

			
# 	X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

	# print("Size of train set: ", X_train.shape)
	# print("Size of validation set: ", X_test.shape)
	# clf = GaussianNB()
	# clf = SVC(kernel='rbf')
# 	clf.fit(X_train, y_train, [len(y_train)])
# 	preds = clf.predict(X_test)
    
    clf.fit(X, Y, [len(Y)])
    preds = clf.predict(X)

# 	correct = 0
# 	for j in range(len(X_test)):
# 		if preds[j]==y_test[j] or preds[j].split(":")[0] == y_test[j].split(":")[0]:
# 				# print("(Predicted, label): ", preds[j],y_test[j], "1")
# 				correct+=1
# 		else:
# 			pass
# 			# print("(Predicted, label): ", preds[j],y_test[j], "0")
            
    correct = 0
    for j in range(len(X)):
        if preds[j]==Y[j] or preds[j].split(":")[0] == Y[j].split(":")[0]:
            print("(Predicted, label): ", preds[j],y_test[j], "1")
            correct+=1
        else:
            print("(Predicted, label): ", preds[j],Y[j], "0")

    print (correct*100.0/len(X))
# 	print(accuracy_score(y_test,preds))

# 	return correct, len(X_test)

In [4]:
data, labels = read_pkls()

['01 - The Beatles - Drive My Car_X.pkl', "03 - The Beatles - You Won't See Me_X.pkl", '04 - The Beatles - Nowhere Man_X.pkl', '06 - The Beatles - The Word_X.pkl', '07 - The Beatles - Michelle_X.pkl', '08 - The Beatles - What Goes On_X.pkl', '09 - The Beatles - Girl_X.pkl', '11 - The Beatles - In My Life_X.pkl', '13 - The Beatles - If I Needed Someone_X.pkl', '14 - The Beatles - Run For Your Life_X.pkl']
['01 - The Beatles - Drive My Car_Y.pkl', "03 - The Beatles - You Won't See Me_Y.pkl", '04 - The Beatles - Nowhere Man_Y.pkl', '06 - The Beatles - The Word_Y.pkl', '07 - The Beatles - Michelle_Y.pkl', '08 - The Beatles - What Goes On_Y.pkl', '09 - The Beatles - Girl_Y.pkl', '11 - The Beatles - In My Life_Y.pkl', '13 - The Beatles - If I Needed Someone_Y.pkl', '14 - The Beatles - Run For Your Life_Y.pkl']


In [5]:
def extract_features_lda(X,Y):
	lda = LDA()
	X_new=lda.fit_transform(X,Y)
	return X_new

In [87]:
# print(data[0].shape)
# print(data[7])
print(labels[6])
# print(len(data))

['N' 'N' 'C:min' 'C:min' 'C:min' 'G:7' 'G:7' 'C:min' 'C:min' 'C:min'
 'C:min' 'C:min' 'F:min' 'F:min' 'F:min' 'F:min' 'F:min' 'Eb' 'Eb' 'Eb'
 'G' 'G' 'C:min' 'C:min' 'C:min' 'G:7' 'G:7' 'C:min' 'C:min' 'C:min'
 'C:min' 'C:min' 'F:min' 'F:min' 'F:min' 'F:min' 'F:min' 'C:min' 'C:min'
 'C:min' 'C:min' 'C:min' 'Eb' 'Eb' 'Eb' 'G:min/5' 'G:min/5' 'F:min/5'
 'F:min/5' 'F:min/5' 'Bb' 'Bb' 'Eb' 'Eb' 'Eb' 'G:min/5' 'G:min/5'
 'F:min/5' 'F:min/5' 'F:min/5' 'Bb' 'Bb' 'C:min' 'C:min' 'C:min' 'G:7'
 'G:7' 'C:min' 'C:min' 'C:min' 'C:min' 'C:min' 'F:min' 'F:min' 'F:min'
 'F:min' 'F:min' 'Eb' 'Eb' 'Eb' 'G' 'G' 'C:min' 'C:min' 'C:min' 'G:7'
 'G:7' 'C:min' 'C:min' 'C:min' 'C:min' 'C:min' 'F:min' 'F:min' 'F:min'
 'F:min' 'F:min' 'C:min' 'C:min' 'C:min' 'C:min' 'C:min' 'Eb' 'Eb' 'Eb'
 'G:min/5' 'G:min/5' 'F:min/5' 'F:min/5' 'F:min/5' 'Bb' 'Bb' 'Eb' 'Eb'
 'Eb' 'G:min/5' 'G:min/5' 'F:min/5' 'F:min/5' 'F:min/5' 'Bb' 'Bb' 'F:min'
 'F:min' 'F:min' 'F:min' 'F:min' 'C' 'C' 'C' 'C' 'C' 'F:min' 'F:min'
 'F:min' 'F:

In [8]:
X_new = extract_features_lda(data[6],labels[6])

/home/aditya/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
/home/aditya/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [5]:
def hmm_classify(X,y):
    lengths = [1]
    n_features = X.shape[1]
    clf = MultinomialHMM(decode='bestfirst', alpha=0.01)
    clf.fit(X, y, lengths)
    print(clf.classes_)
    print(clf.predict(X))

In [9]:
def perceptron_classify(X,y, X_test):
    clf = StructuredPerceptron(verbose=True, random_state=37, max_iter=15)
    clf.fit(X, y, [len(y)])
#     print(clf.classes_)
    return clf.predict(X_test)

In [ ]:
hmm_classify(X_new.astype('float64'),labels[6])

In [11]:
perceptron_classify(X_new.astype('float64'),labels[6])

['Ab' 'Bb' 'C' 'C:min' 'Eb' 'F:min' 'F:min/5' 'G' 'G:7' 'G:min/5' 'N']
['Bb' 'Bb' 'C:min' 'C:min' 'C:min' 'G:7' 'G:7' 'C:min' 'C:min' 'C:min'
 'C:min' 'C:min' 'F:min' 'F:min' 'F:min' 'F:min' 'F:min' 'Eb' 'Eb' 'Eb'
 'G' 'G' 'C:min' 'C:min' 'C:min' 'G:7' 'G:7' 'C:min' 'C:min' 'C:min'
 'C:min' 'C:min' 'F:min' 'F:min' 'F:min' 'F:min' 'F:min' 'C:min' 'C:min'
 'C:min' 'C:min' 'C:min' 'Eb' 'Eb' 'Eb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb'
 'Eb' 'Eb' 'Eb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'C:min' 'C:min' 'C:min'
 'G:7' 'G:7' 'C:min' 'C:min' 'C:min' 'C:min' 'C:min' 'F:min' 'F:min'
 'F:min' 'F:min' 'F:min' 'Eb' 'Eb' 'Eb' 'G' 'G' 'C:min' 'C:min' 'C:min'
 'G:7' 'G:7' 'C:min' 'C:min' 'C:min' 'C:min' 'C:min' 'F:min' 'F:min'
 'F:min' 'F:min' 'F:min' 'C:min' 'C:min' 'C:min' 'C:min' 'C:min' 'Eb' 'Eb'
 'Eb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'Bb' 'Eb' 'Eb' 'Eb' 'Bb' 'Bb' 'Bb'
 'Bb' 'Bb' 'Bb' 'Bb' 'F:min' 'F:min' 'F:min' 'F:min' 'F:min' 'C' 'C' 'C'
 'C' 'C' 'F:min' 'F:min' 'F:min' 'F:min' 'F:min' 'C' 'C' 'C' 'C' 

In [29]:
for i in range(len(data)):
    X_new = extract_features_lda(data[i],labels[i])
    clf = StructuredPerceptron(verbose=False, random_state=37, max_iter=15)
    evaluate_classifier(X_new.astype('float64'),labels[i],clf)

/home/aditya/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


96.66666666666667
80.32786885245902
74.74747474747475


/home/aditya/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)


90.9090909090909
91.83673469387755
97.0873786407767
88.17204301075269
98.87640449438203
93.10344827586206
96.42857142857143


In [6]:
dataset = np.load('dataset_2016-05-15.npz')
X_train_orig, Y_train_orig, X_valid_orig, Y_valid_orig, X_test_orig, Y_test_orig = dataset['X_train'], dataset['Y_train'],     dataset['X_valid'], dataset['Y_valid'],     dataset['X_test'], dataset['Y_test']
print(X_train_orig.shape, X_valid_orig.shape, X_test_orig.shape)
print(Y_train_orig.shape, Y_valid_orig.shape, Y_test_orig.shape)

(368114, 115) (134670, 115) (128936, 115)
(368114, 12) (134670, 12) (128936, 12)


In [7]:
print(np.unique(Y_train_orig,axis=0))
labels = np.unique(Y_train_orig,axis=0)
print(labels.shape)
label_vec_map = {}
for i, vec in enumerate(labels):
    vec = vec.flatten()
    vec = ''.join([str(i) for i in vec])
    label_vec_map[vec] = i
print(label_vec_map)

Y_train_new = []
for i, x in enumerate(X_train_orig):
    y = Y_train_orig[i].flatten()
    y = ''.join([str(i) for i in y])
    Y_train_new.append(label_vec_map[y])
print(Y_train_new)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 0 1 ... 1 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 1 0 0]]
(162, 12)
{'000000000000': 0, '000000000001': 1, '000000000010': 2, '000000000100': 3, '000000010000': 4, '000000100001': 5, '000001000000': 6, '000001001001': 7, '000010000000': 8, '000010000100': 9, '000010000101': 10, '000010001001': 11, '000010001011': 12, '000010001101': 13, '000010010001': 14, '000010010010': 15, '000010011001': 16, '000010100001': 17, '000010100101': 18, '000010110001': 19, '000100001000': 20, '000100001001': 21, '000100010001': 22, '000100010010': 23, '000100100001': 24, '000100100010': 25, '000100100011': 26, '000100100100': 27, '000100100101': 28, '000100101001': 29, '000101010010': 30, '000110001001': 31, '001000000000': 32, '001000000001': 33, '001000000100': 34, '001000000101': 35, '001000010000': 36, '001000010001': 37, '001000010010': 38, '001000010100': 39, '001000010101': 40, '001000100001': 41, '001000100010': 42, '001000100011': 43,

In [10]:
X_new = extract_features_lda(X_train_orig[:2000], Y_train_new[:2000])
print("Finished lda")
print(X_new.shape)
preds = perceptron_classify(X_new[:1000].astype('float64'),Y_train_new[:1000], X_new[1000:2000].astype('float64'))
acc = accuracy_score(Y_train_new[1000:2000], preds)
print(acc)

Finished lda
(2000, 19)
Iteration  1... loss = 0.9920
Iteration  2... loss = 0.2770
Iteration  3... loss = 0.1160
Iteration  4... loss = 0.0870
Iteration  5... loss = 0.0460
Iteration  6... loss = 0.0440
Iteration  7... loss = 0.0400
Iteration  8... loss = 0.0430
Iteration  9... loss = 0.0430
Iteration 10... loss = 0.0330
Iteration 11... loss = 0.0290
Iteration 12... loss = 0.0320
Iteration 13... loss = 0.0320
Iteration 14... loss = 0.0280
Iteration 15... loss = 0.0270
0.909


/home/aditya/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
/home/aditya/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
